name: stride
channels:
  - conda-forge
  - defaults
dependencies:
  - pytest
  - pytest-cov
  - pytest-runner
  - pytorch
  - pyyaml>=5.4
  - pyqt5-sip
  - pyzmq>=22.1
  - scikit-image
  - scipy>=1.6
  - sphinx
  - sphinx_rtd_theme
  - tornado>=6.1
  - tqdm
  - traitsui
  - ipympl
  - uvloop
  - zlib
  - zict>=3.0.0
  - pip:
      - devito>=4.6
      - ndsplines
      - python-daemon
      - py-libnuma
      - resampy
      - tblib
